#ifndef GUARD_CONSTANTS_APRICORN_TREE_H
#define GUARD_CONSTANTS_APRICORN_TREE_H

// Apricorns
#define APRICORN_RED       0
#define APRICORN_BLUE      1
#define APRICORN_YELLOW    2
#define APRICORN_GREEN     3
#define APRICORN_PINK      4
#define APRICORN_WHITE     5
#define APRICORN_BLACK     6

#define APRICORN_COUNT     7

// Trees
#define APRICORN_TREE_NONE 0

#define APRICORN_TREE_ROUTE101_RED_TREE    1
#define APRICORN_TREE_ROUTE101_WHITE_TREE  2
#define APRICORN_TREE_ROUTE101_BLACK_TREE  3
#define APRICORN_TREE_ROUTE101_GREEN_TREE  4
#define APRICORN_TREE_ROUTE101_YELLOW_TREE 5
#define APRICORN_TREE_ROUTE101_PINK_TREE   6
#define APRICORN_TREE_ROUTE101_BLUE_TREE   7

#define APRICORN_TREE_ROUTE102_RED_TREE    8
#define APRICORN_TREE_ROUTE102_WHITE_TREE  9
#define APRICORN_TREE_ROUTE102_BLACK_TREE  10
#define APRICORN_TREE_ROUTE102_GREEN_TREE  11
#define APRICORN_TREE_ROUTE102_YELLOW_TREE 12
#define APRICORN_TREE_ROUTE102_PINK_TREE   13
#define APRICORN_TREE_ROUTE102_BLUE_TREE   14

#define APRICORN_TREE_ROUTE116_RED_TREE    15
#define APRICORN_TREE_ROUTE116_WHITE_TREE  16
#define APRICORN_TREE_ROUTE116_BLACK_TREE  17
#define APRICORN_TREE_ROUTE116_GREEN_TREE  18
#define APRICORN_TREE_ROUTE116_YELLOW_TREE 19
#define APRICORN_TREE_ROUTE116_PINK_TREE   20
#define APRICORN_TREE_ROUTE116_BLUE_TREE   21

#define APRICORN_TREE_PETALBURG_WOODS_RED_TREE    22
#define APRICORN_TREE_PETALBURG_WOODS_WHITE_TREE  23
#define APRICORN_TREE_PETALBURG_WOODS_BLACK_TREE  24
#define APRICORN_TREE_PETALBURG_WOODS_GREEN_TREE  25
#define APRICORN_TREE_PETALBURG_WOODS_YELLOW_TREE 26
#define APRICORN_TREE_PETALBURG_WOODS_PINK_TREE   27
#define APRICORN_TREE_PETALBURG_WOODS_BLUE_TREE   28

#define APRICORN_TREE_DEEP_PETALBURG_WOODS_RED_TREE    29
#define APRICORN_TREE_DEEP_PETALBURG_WOODS_WHITE_TREE  30
#define APRICORN_TREE_DEEP_PETALBURG_WOODS_BLACK_TREE  31
#define APRICORN_TREE_DEEP_PETALBURG_WOODS_GREEN_TREE  32
#define APRICORN_TREE_DEEP_PETALBURG_WOODS_YELLOW_TREE 33
#define APRICORN_TREE_DEEP_PETALBURG_WOODS_PINK_TREE   34
#define APRICORN_TREE_DEEP_PETALBURG_WOODS_BLUE_TREE   35

#define APRICORN_TREE_ROUTE120_RED_TREE    36
#define APRICORN_TREE_ROUTE120_WHITE_TREE  37
#define APRICORN_TREE_ROUTE120_BLACK_TREE  38
#define APRICORN_TREE_ROUTE120_GREEN_TREE  39
#define APRICORN_TREE_ROUTE120_YELLOW_TREE 40
#define APRICORN_TREE_ROUTE120_PINK_TREE   41
#define APRICORN_TREE_ROUTE120_BLUE_TREE   42

#define APRICORN_TREE_COUNT 56

#endif //GUARD_CONSTANTS_APRICORN_TREE_H
