#ifndef GUARD_CONSTANTS_APRICORN_TREE_H
#define GUARD_CONSTANTS_APRICORN_TREE_H

// Apricorns
#define APRICORN_RED       0
#define APRICORN_BLUE      1
#define APRICORN_YELLOW    2
#define APRICORN_GREEN     3
#define APRICORN_PINK      4
#define APRICORN_WHITE     5
#define APRICORN_BLACK     6

#define APRICORN_COUNT     7

// Trees
#define APRICORN_TREE_NONE            0
#define APRICORN_TREE_EMPTY           1

// Route 101
#define RED_APRICORN_TREE_ROUTE101    2
#define BLUE_APRICORN_TREE_ROUTE101   3
#define PINK_APRICORN_TREE_ROUTE101   4
#define WHITE_APRICORN_TREE_ROUTE101  5
#define BLACK_APRICORN_TREE_ROUTE101  6
#define GREEN_APRICORN_TREE_ROUTE101  7
#define YELLOW_APRICORN_TREE_ROUTE101 8

// Petalburg Woods
#define RED_APRICORN_TREE_PETALBURG_WOODS    9
#define BLUE_APRICORN_TREE_PETALBURG_WOODS   10
#define PINK_APRICORN_TREE_PETALBURG_WOODS   11
#define WHITE_APRICORN_TREE_PETALBURG_WOODS  12
#define BLACK_APRICORN_TREE_PETALBURG_WOODS  13
#define GREEN_APRICORN_TREE_PETALBURG_WOODS  14
#define YELLOW_APRICORN_TREE_PETALBURG_WOODS 15

// Deep Petalburg Woods
#define RED_APRICORN_TREE_DEEP_PETALBURG_WOODS    16
#define BLUE_APRICORN_TREE_DEEP_PETALBURG_WOODS   17
#define PINK_APRICORN_TREE_DEEP_PETALBURG_WOODS   18
#define WHITE_APRICORN_TREE_DEEP_PETALBURG_WOODS  19
#define BLACK_APRICORN_TREE_DEEP_PETALBURG_WOODS  20
#define GREEN_APRICORN_TREE_DEEP_PETALBURG_WOODS  21
#define YELLOW_APRICORN_TREE_DEEP_PETALBURG_WOODS 22

#define APRICORN_TREE_COUNT           32

#endif //GUARD_CONSTANTS_APRICORN_TREE_H
