#ifndef GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H
#define GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H

enum Cutscenes
{
    CUTSCENE_MAXIE_MT_CHIMNEY,
    CUTSCENE_MAXIE_MAGMA_BASE,
    CUTSCENE_ARCHIE_SEAFLOOR_CAVERN,
    CUTSCENE_COUNT,
};

#endif // GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H