#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10
#define HIDDEN_WILD_COUNT   3

#define NUM_ALTERING_CAVE_TABLES 9
#define NUM_STRANGE_SPACE_PLAINS_TABLES 6
#define NUM_STRANGE_SPACE_DESERT_TABLES 3
#define NUM_STRANGE_SPACE_ICE_TABLES 2
#define NUM_STRANGE_SPACE_VOLCANO_TABLES 3
#define NUM_STRANGE_SPACE_CAVE_TABLES 2
#define NUM_STRANGE_SPACE_FOREST_TABLES 3
#define NUM_STRANGE_SPACE_MOUNTAIN_TABLES 3
#define NUM_STRANGE_SPACE_LAKE_TABLES 3
#define NUM_STRANGE_SPACE_VOID_TABLES 3

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
