[items]
"./graphics/mining_minigame/items/heart_scale.4bpp" = "MININGID_HEART_SCALE"
"./graphics/mining_minigame/items/star_piece.4bpp" = "MININGID_STAR_PIECE"
"./graphics/mining_minigame/items/red_shard.4bpp" = "MININGID_RED_SHARD"
"./graphics/mining_minigame/items/revive.4bpp" = "MININGID_REVIVE"
"./graphics/mining_minigame/items/light_clay.4bpp" = "MININGID_LIGHT_CLAY"
"./graphics/mining_minigame/items/heat_rock.4bpp" =  "MININGID_HEAT_ROCK"
"./graphics/mining_minigame/items/damp_rock.4bpp" = "MININGID_DAMP_ROCK"
"./graphics/mining_minigame/items/blue_shard.4bpp" = "MININGID_BLUE_SHARD"
"./graphics/mining_minigame/items/oval_stone.4bpp" = "MININGID_OVAL_STONE"
"./graphics/mining_minigame/items/ever_stone.4bpp" = "MININGID_EVER_STONE"
"./graphics/mining_minigame/items/hard_stone.4bpp" = "MININGID_HARD_STONE"
"./graphics/mining_minigame/items/revive_max.4bpp" = "MININGID_REVIVE_MAX"
"./graphics/mining_minigame/items/iron_ball.4bpp" = "MININGID_IRON_BALL"
"./graphics/mining_minigame/items/icy_rock.4bpp" = "MININGID_ICY_ROCK"
"./graphics/mining_minigame/items/smooth_rock.4bpp" = "MININGID_SMOOTH_ROCK"
"./graphics/mining_minigame/items/yellow_shard.4bpp" = "MININGID_YELLOW_SHARD"
"./graphics/mining_minigame/items/green_shard.4bpp" = "MININGID_GREEN_SHARD"
"./graphics/mining_minigame/items/leaf_stone.4bpp" = "MININGID_LEAF_STONE"
"./graphics/mining_minigame/items/fire_stone.4bpp" = "MININGID_FIRE_STONE"
"./graphics/mining_minigame/items/water_stone.4bpp" = "MININGID_WATER_STONE"
"./graphics/mining_minigame/items/thunder_stone.4bpp" = "MININGID_THUNDER_STONE"
"./graphics/mining_minigame/items/moon_stone.4bpp" = "MININGID_MOON_STONE"
"./graphics/mining_minigame/items/sun_stone.4bpp" = "MININGID_SUN_STONE"
"./graphics/mining_minigame/items/odd_key_stone.4bpp" = "MININGID_ODD_KEY_STONE"
"./graphics/mining_minigame/items/skull_fossil.4bpp" = "MININGID_SKULL_FOSSIL"
"./graphics/mining_minigame/items/armor_fossil.4bpp" = "MININGID_ARMOR_FOSSIL"

[stones]
"./graphics/mining_minigame/stones/stone_2x2.4bpp" = "MININGID_STONE_2x2"
"./graphics/mining_minigame/stones/stone_3x3.4bpp" = "MININGID_STONE_3x3"
"./graphics/mining_minigame/stones/stone_1x4.4bpp" = "MININGID_STONE_1x4"
"./graphics/mining_minigame/stones/stone_4x1.4bpp" = "MININGID_STONE_4x1"
"./graphics/mining_minigame/stones/stone_2x4.4bpp" = "MININGID_STONE_2x4"
"./graphics/mining_minigame/stones/stone_4x2.4bpp" = "MININGID_STONE_4x2"
"./graphics/mining_minigame/stones/stone_snake1.4bpp" = "MININGID_STONE_SNAKE1"
"./graphics/mining_minigame/stones/stone_snake2.4bpp" = "MININGID_STONE_SNAKE2"
"./graphics/mining_minigame/stones/stone_mushroom1.4bpp" = "MININGID_STONE_MUSHROOM1"
"./graphics/mining_minigame/stones/stone_mushroom2.4bpp" = "MININGID_STONE_MUSHROOM2"
