@ Contest move effect descriptions

gText_HighlyAppealingMove:: @ 827CB82
	.string "A highly appealing move.$"

gText_UserMoreEasilyStartled:: @ 827CB9B
	.string "After this move, the user is\nmore easily startled.$"

gText_GreatAppealButNoMoreToEnd:: @ 827CBCE
	.string "Makes a great appeal, but\nallows no more to the end.$"

gText_UsedRepeatedlyWithoutBoringJudge:: @ 827CC03
	.string "Can be repeatedly used\nwithout boring the Judge.$"

gText_AvoidStartledByOthersOnce:: @ 827CC34
	.string "Can avoid being startled\nby others once.$"

gText_AvoidStartledByOthers:: @ 827CC5D
	.string "Can avoid being startled\nby others.$"

gText_AvoidStartledByOthersLittle:: @ 827CC81
	.string "Can avoid being startled\nby others a little.$"

gText_UserLessLikelyStartled:: @ 827CCAE
	.string "After this move, the user is\nless likely to be startled.$"

gText_SlightlyStartleFrontMon:: @ 827CCE7
	.string "Slightly startles the\nPokémon in front.$"

gText_SlightlyStartleAppealed:: @ 827CD0F
	.string "Slightly startles those\nthat have made appeals.$"

gText_StartleAppealedBeforeUser:: @ 827CD3F
	.string "Startles the Pokémon that\nappealed before the user.$"

gText_StartleAllAppealed:: @ 827CD73
	.string "Startles all Pokémon that\nhave done their appeals.$"

gText_BadlyStartleFrontMon:: @ 827CDA6
	.string "Badly startles the\nPokémon in front.$"

gText_BadlyStartleAppealed:: @ 827CDCB
	.string "Badly startles those that\nhave made appeals.$"

gText_StartleAppealedBeforeUser2:: @ 827CDF8
	.string "Startles the Pokémon that\nappealed before the user.$"

gText_StartleAllAppealed2:: @ 827CE2C
	.string "Startles all Pokémon that\nhave done their appeals.$"

gText_ShiftJudgesAttentionFromOthers:: @ 827CE5F
	.string "Shifts the Judge's\nattention from others.$"

gText_StartleMonHasJudgesAttention:: @ 827CE89
	.string "Startles the Pokémon that\nhas the Judge's attention.$"

gText_JamOthersMissesTurn:: @ 827CEBE
	.string "Jams the others, and misses\none turn of appeals.$"

gText_StartleMonsMadeSameTypeAppeal:: @ 827CEEF
	.string "Startles Pokémon that\nmade a same-type appeal.$"

gText_BadlyStartleCoolAppeals:: @ 827CF1E
	.string "Badly startles Pokémon\nthat made Cool appeals.$"

gText_BadlyStartleBeautyAppeals:: @ 827CF4D
	.string "Badly startles Pokémon\nthat made Beauty appeals.$"

gText_BadlyStartleCuteAppeals:: @ 827CF7E
	.string "Badly startles Pokémon\nthat made Cute appeals.$"

gText_BadlyStartleSmartAppeals:: @ 827CFAD
	.string "Badly startles Pokémon\nthat made Smart appeals.$"

gText_BadlyStartleToughAppeals:: @ 827CFDD
	.string "Badly startles Pokémon\nthat made Tough appeals.$"

gText_MakeMonAfterUserNervous:: @ 827D00D
	.string "Makes one Pokémon after\nthe user nervous.$"

gText_MakeAllMonsAfterUserNervous:: @ 827D037
	.string "Makes all Pokémon after\nthe user nervous.$"

gText_WorsenConditionOfThoseMadeAppeals:: @ 827D061
	.string "Worsens the condition of\nthose that made appeals.$"

gText_BadlyStartleMonsGoodCondition:: @ 827D093
	.string "Badly startles Pokémon in\ngood condition.$"

gText_AppealGreatIfPerformedFirst:: @ 827D0BD
	.string "The appeal works great if\nperformed first.$"

gText_AppealGreatIfPerformedLast:: @ 827D0E8
	.string "The appeal works great if\nperformed last.$"

gText_AppealAsGoodAsThoseBeforeIt:: @ 827D112
	.string "Makes the appeal as good\nas those before it.$"

gText_AppealAsGoodAsOneBeforeIt:: @ 827D13F
	.string "Makes the appeal as good\nas the one before it.$"

gText_AppealBetterLaterItsPerformed:: @ 827D16E
	.string "The appeal works better\nthe later it is performed.$"

gText_AppealVariesDependingOnTiming:: @ 827D1A1
	.string "The appeal's quality varies\ndepending on its timing.$"

gText_WorksWellIfSameTypeAsBefore:: @ 827D1D6
	.string "Works well if it's the same\ntype as the one before.$"

gText_WorksWellIfDifferentTypeAsBefore:: @ 827D20A
	.string "Works well if different in\ntype than the one before.$"

gText_AffectedByAppealInFront:: @ 827D23F
	.string "Affected by how well the\nappeal in front goes.$"

gText_UpsConditionHelpsPreventNervousness:: @ 827D26E
	.string "Ups the user's condition.\nHelps prevent nervousness.$"

gText_AppealWorksWellIfConditionGood:: @ 827D2A3
	.string "The appeal works well if the\nuser's condition is good.$"

gText_NextAppealMadeEarlier:: @ 827D2DA
	.string "The next appeal can be\nmade earlier next turn.$"

gText_NextAppealMadeLater:: @ 827D309
	.string "The next appeal can be\nmade later next turn.$"

gText_TurnOrderMoreEasilyScrambled:: @ 827D336
	.string "Makes the next turn's order\nmore easily scrambled.$"

gText_ScrambleOrderOfNextAppeals:: @ 827D369
	.string "Scrambles the order of\nappeals on the next turn.$"

gText_AppealExcitesAudienceInAnyContest:: @ 827D39A
	.string "An appeal that excites the\naudience in any Contest.$"

gText_BadlyStartlesMonsGoodAppeals:: @ 827D3CE
	.string "Badly startles all Pokémon\nthat made good appeals.$"

gText_AppealBestMoreCrowdExcited:: @ 827D401
	.string "The appeal works best the\nmore the crowd is excited.$"

gText_TemporarilyStopCrowdExcited:: @ 827D436
	.string "Temporarily stops the\ncrowd from growing excited.$"

@ Unused move names

gText_RainDance:: @ 827D468
	.string "Rain Dance$"

gText_Rage:: @ 827D473
	.string "Rage$"

gText_FocusEnergy:: @ 827D478
	.string "Focus Energy$"

gText_Hypnosis:: @ 827D485
	.string "Hypnosis$"

gText_Softboiled:: @ 827D48E
	.string "SoftBoiled$"

gText_HornAttack:: @ 827D499
	.string "Horn Attack$"

gText_SwordsDance:: @ 827D4A5
	.string "Swords Dance$"

gText_Conversion:: @ 827D4B2
	.string "Conversion$"

gText_SunnyDay:: @ 827D4BD
	.string "Sunny Day$"

gText_Rest2:: @ 827D4C7
	.string "Rest$"

gText_Vicegrip:: @ 827D4CC
	.string "ViceGrip$"

gText_DefenseCurl:: @ 827D4D5
	.string "Defense Curl$"

gText_LockOn:: @ 827D4E2
	.string "Lock-On$"

@ Contest type names

gContestMoveTypeCoolText:: @ 827D4EA
	.string "Cool$"

gContestMoveTypeBeautyText:: @ 827D4EF
	.string "Beauty$"

gContestMoveTypeCuteText:: @ 827D4F6
	.string "Cute$"

gContestMoveTypeSmartText:: @ 827D4FB
	.string "Smart$"

gContestMoveTypeToughText:: @ 827D501
	.string "Tough$"

gText_AppealNumWhichMoveWillBePlayed:: @ 827D507
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "Which move will be played?$"

gText_AppealNumButItCantParticipate::
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "But it can't participate!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} appealed with\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} was watching\n"
	.string "the others.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "We're all out of\n"
	.string "Appeal Time!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed:: @ 827D5C1
	.string "But the appeal was\n"
	.string "jammed.$"

gText_FollowedAnotherMonsLead:: @ 827D5DC
	.string "It followed another\n"
	.string "Pokémon's lead.$"

gText_ButItMessedUp:: @ 827D600
	.string "But it messed up.$"

gText_WentBetterThanUsual:: @ 827D612
	.string "It went better than\n"
	.string "usual.$"

gText_JudgeLookedAwayForSomeReason:: @ 827D62D
	.string "The Judge looked away\n"
	.string "for some reason.$"

gText_WorkedHardToBuildOnPastMistakes:: @ 827D654
	.string "It worked hard to build on\n"
	.string "past mistakes.$"

gText_CantMakeAnyMoreMoves:: @ 827D67E
	.string "It can't make any more\n"
	.string "moves.$"

gText_WorkedFrighteninglyWell:: @ 827D69C
	.string "It worked frighteningly\n"
	.string "well.$"

gText_WorkedHardAsStandoutMon:: @ 827D6BA
	.string "It worked as hard as the\n"
	.string "standout Pokémon.$"

gText_JudgedLookedOnExpectantly:: @ 827D6E5
	.string "The Judge looked on\n"
	.string "expectantly.$"

gText_WorkedRatherWell:: @ 827D706
	.string "It worked rather well.$"

gText_WorkedLittleBetterThanUsual:: @ 827D71D
	.string "It worked a little better\n"
	.string "than usual.$"

@ Round result texts

gText_MonFailedToStandOutAtAll:: @ 827D743
	.string "{STR_VAR_1} failed to\n"
	.string "stand out at all…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch:: @ 827D764
	.string "{STR_VAR_1} didn't stand\n"
	.string "out very much…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention:: @ 827D785
	.string "{STR_VAR_1} caught a\n"
	.string "little attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention:: @ 827D7A5
	.string "{STR_VAR_1} attracted a\n"
	.string "lot of attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention:: @ 827D7C8
	.string "{STR_VAR_1} commanded\n"
	.string "total attention.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal:: @ 827D7E8
	.string "{STR_VAR_1} hasn't made\n"
	.string "its appeal.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2:: @ 827D805
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString:: @ 827D830
	.string "$"

gText_JudgesViewsOnMonHeldFirm:: @ 827D831
	.string "The Judge 's views on\n"
	.string "{STR_VAR_1} held firm.$"

gText_MonsXChangedPerceptions:: @ 827D855
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "changed perceptions.$"

gText_MonsAppealEffectWoreOff:: @ 827D872
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"

gText_SpecialAppealsEffectWoreOff:: @ 827D88F
	.string "The special appeal's\n"
	.string "effect wore off.$"

gText_EveryonesAppealsMadeToLookSame:: @ 827D8B5
	.string "Everyone's appeals were\n"
	.string "made to look the same.$"

gText_CheapenedMonsAppeal:: @ 827D8E4
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_CheapenedAppealOfThoseAhead:: @ 827D8FE
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_StoleAttentionAwayFromMon:: @ 827D926
	.string "It stole attention away\n"
	.string "from {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2:: @ 827D947
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_SeverelyCheapenedOtherAppeals:: @ 827D961
	.string "It severely cheapened\n"
	.string "other appeals.$"

gText_AnticipationSwelledForMonsAppealNext:: @ 827D986
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_CheapenedAppealOfThoseAhead2:: @ 827D9B1
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_CheapenedJudgesFavoriteAppeal:: @ 827D9D9
	.string "It cheapened the Judge's\n"
	.string "favorite appeal.$"

gText_AppealsOfOthersCheapenedByHalf:: @ 827DA03
	.string "The appeals of others\n"
	.string "were cheapened by half.$"

gText_StoodOutToMakeUpForBeingJammed:: @ 827DA31
	.string "It stood out to make up\n"
	.string "for being jammed.$"

gText_CantParticipateInAppealsAnyMore:: @ 827DA5B
	.string "It can't participate in\n"
	.string "appeals any more.$"

gText_TouchedJudgeForFantasticAppeal:: @ 827DA85
	.string "It touched the Judge for\n"
	.string "a fantastic appeal.$"

gText_AnticipationRoseForUpcomingAppeals:: @ 827DAB2
	.string "Anticipation rose for\n"
	.string "upcoming appeals.$"

gText_StoodOutAsMuchAsSpecialAppeals:: @ 827DADA
	.string "It stood out as much as\n"
	.string "special appeals.$"

gText_StoodOutAsMuchAsMon:: @ 827DB03
	.string "It stood out as much as\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable:: @ 827DB1F
	.string "Jammed appeals were made\n"
	.string "even less noticeable.$"

gText_EveryonesAppealsMadeSame:: @ 827DB4E
	.string "Everyone's appeals were\n"
	.string "made the same.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "It became more conscious\n"
	.string "of the other Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} can't make an\n"
	.string "appeal after this.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "It settled down just a\n"
	.string "little bit.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "It became oblivious to\n"
	.string "the other Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "It became less aware of\n"
	.string "the other Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "It stopped caring about\n"
	.string "other Pokémon much.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "It tried to startle the\n"
	.string "other Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "It tried to dazzle the\n"
	.string "others.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon:: @ 827DD12
	.string "The Judge looked away\n"
	.string "from {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "It tried to unnerve the\n"
	.string "next Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} became\n"
	.string "nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "The appeal tried to\n"
	.string "unnerve waiting Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell:: @ 827DDC7
	.string "It taunted Pokémon\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} regained its\n"
	.string "form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell:: @ 827DE14
	.string "It tried to jam Pokémon\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "The standout {STR_VAR_1}\n"
	.string "hustled even more.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "The largely unnoticed\n"
	.string "{STR_VAR_1} worked hard.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "It worked as much as\n"
	.string "Pokémon before it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "It worked as much as the\n"
	.string "preceding Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1}'s appeal was\n"
	.string "a dud.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not work very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "It's the same type as the\n"
	.string "Pokémon before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "It's not the same type as\n"
	.string "the one before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "It stood out much more\n"
	.string "than the Pokémon before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "It didn't do as well as the\n"
	.string "Pokémon before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1}'s condition\n"
	.string "rose above usual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1}'s hot status\n"
	.string "made it a great appeal!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "It moved up in line for\n"
	.string "the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "It moved back in line once\n"
	.string "for the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "It scrambled up the\n"
	.string "order for the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly:: @ 827E2FE
	.string "The Judge looked at\n"
	.string "{STR_VAR_1} expectantly.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "The appeal combo went\n"
	.string "over well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "The appeal combo went\n"
	.string "over very well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "The appeal combo went\n"
	.string "over excellently.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} managed to\n"
	.string "avert its gaze.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} managed to\n"
	.string "avoid seeing it.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} isn't fazed\n"
	.string "by that sort of thing.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} became a\n"
	.string "little distracted.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "It tried to startle the\n"
	.string "other Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} looked down\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} turned back\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} couldn't help\n"
	.string "uttering a cry.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} couldn't help\n"
	.string "leaping up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} tripped over\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} was too\n"
	.string "nervous to move.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "But it messed up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "But it failed to make\n"
	.string "the target nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "But it failed to make\n"
	.string "anyone nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "But it was ignored…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "But it couldn't improve\n"
	.string "its condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Its bad condition\n"
	.string "resulted in a weak appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} was\n"
	.string "unaffected.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} disappointed\n"
	.string "by repeating an appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "went over great.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "didn't go over well here…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "got the crowd going.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} can't appeal\n"
	.string "next turn…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "It attracted the crowd's\n"
	.string "attention.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "The crowd continues to\n"
	.string "watch {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}'s\n"
	.string "{STR_VAR_2} is ignored.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "shyness$"

gText_Contest_Anxiety::
	.string "anxiety$"

gText_Contest_Laziness::
	.string "laziness$"

gText_Contest_Hesitancy::
	.string "hesitancy$"

gText_Contest_Fear::
	.string "fear$"

gText_Contest_Coolness:: @ 827E85F
	.string "coolness$"

gText_Contest_Beauty:: @ 827E868
	.string "beauty$"

gText_Contest_Cuteness:: @ 827E86F
	.string "cuteness$"

gText_Contest_Smartness:: @ 827E878
	.string "smartness$"

gText_Contest_Toughness:: @ 827E882
	.string "toughness$"

@ Unused
gText_Tension:: @ 827E88C
	.string "Tension$"

gText_CoolMove:: @ 827E894
	.string "Cool Move$"

gText_BeautyMove:: @ 827E89E
	.string "Beauty Move$"

gText_CuteMove:: @ 827E8AA
	.string "Cute Move$"

gText_SmartMove:: @ 827E8B4
	.string "Smart Move$"

gText_ToughMove:: @ 827E8BF
	.string "Tough Move$"

gText_3QuestionMarks:: @ 827E8CA
	.string "???$"
